# Generated by Django 4.1.4 on 2023-02-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium')], default='Free', max_length=10),
        ),
    ]
